[metadata]
name = v2i_rsu_monitor
version = 0.1.0

[options]
packages = find:
install_requires =
    pycmssdk
    PyQt5

[develop]
script_dir=$base/lib/v2i_rsu_monitor

[install]
install_scripts=$base/lib/v2i_rsu_monitor

[options.data_files]
share/ament_index/resource_index/packages =
    resource/v2i_rsu_monitor
share/v2i_rsu_monitor =
    package.xml
share/v2i_rsu_monitor/launch =
    launch/rsu_monitor_launch.py

[options.entry_points]
console_scripts =
    rsu_monitor = v2i_rsu_monitor.rsu_monitor_node:main
    replay_logs = v2i_rsu_monitor.replay:main
